#! /bin/bash -e

# Usage: ./ber_rebuild.bash [SAMPLE_RATE_VERSION]
#   SAMPLE_RATE_VERSION: 48 or 16 (selects the eband5ms table in denoise.c). Defaults to 16.
SAMPLE_RATE_VERSION="${1:-16}"
if [[ "$SAMPLE_RATE_VERSION" != "48" && "$SAMPLE_RATE_VERSION" != "16" ]]; then
    echo "❌ Invalid SAMPLE_RATE_VERSION '$SAMPLE_RATE_VERSION' (must be 48 or 16)"
    exit 1
fi
echo "Building with SAMPLE_RATE_VERSION=${SAMPLE_RATE_VERSION}"

echo "🔄 Cleaning build artifacts..."
rm -rf ./build
rm -rf ./__pycache__
rm -rf ./pyrnnoise.egg-info
rm -rf ./pyrnnoise/build
rm -rf ./pyrnnoise/__pycache__
rm -f  ./pyrnnoise/librnnoise.so

echo "Prepare RNNoise repo (git submodule) (TODO: only run if folder does not exist)"
#git submodule update --init
#git checkout v0.2

echo "🛠️ Running CMake (configure)..."
cmake -B pyrnnoise/build -DCMAKE_BUILD_TYPE=Release -DSAMPLE_RATE_VERSION="${SAMPLE_RATE_VERSION}"

echo "🔨 Running CMake (build + install target)..."
cmake --build pyrnnoise/build --target install

echo "📝 Recording build config (SAMPLE_RATE_VERSION=${SAMPLE_RATE_VERSION}) for pyrnnoise/rnnoise.py..."
cat > pyrnnoise/_build_config.py <<EOF
# Auto-generated by ber_rebuild.bash - do not edit by hand.
SAMPLE_RATE_VERSION = ${SAMPLE_RATE_VERSION}
EOF

echo "🐍 Building Python package..."
python setup.py build

echo "✅ Build completed successfully."
