name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g. 0.0.1)"
        required: true

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - {
          #     name: Windows Latest MSVC,
          #     os: windows-latest,
          #     cc: cl,
          #     cxx: cl,
          #     artifact_prefix: win,
          #   }
          # - {
          #     name: macOS Latest Clang,
          #     os: macos-latest,
          #     cc: clang,
          #     cxx: clang++,
          #     artifact_prefix: macos,
          #   }
          - {
              name: Ubuntu Latest GCC,
              os: ubuntu-latest,
              cc: gcc,
              cxx: g++,
              artifact_prefix: linux,
            }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{runner.workspace}}/build --target install --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.artifact_prefix }}-pyrnnoise
          path: |
            ${{runner.workspace}}/pyrnnoise

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v3
